language: python
matrix:
    include:
    - python: "3.5"
      env: BLURB=true CHERRY_PICKER=false
    - python: "3.6"
      env: BLURB=true CHERRY_PICKER=true

sudo: false
cache: pip

before_install:
    - pip install --upgrade flit
install:
    - |
        if [[ $CHERRY_PICKER == true ]]; then
            pushd cherry_picker
            flit install
            popd
    - |
        if [[ $BLURB == true ]]; then
            pushd blurb
            flit install
            popd
script:
    - |
        if [[ $CHERRY_PICKER == true ]]; then
            pytest cherry_picker/test.py -v
    - |
        if [[ $BLURB == true ]]; then
            blurb test
